version: '3.8'

services:
  telegram_volleyball_bot:
    image: ${DOCKER_REPO}/vb-telegram-bot:${VERSION}
    pull_policy: if_not_present
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      ADMIN_CHAT_ID: ${ADMIN_CHAT_ID}
    volumes:
      - ./data:/app/data
    networks:
      - vb_telegram_bot_network

volumes:
  data:

networks:
  vb_telegram_bot_network:
